FROM xiaokexiang/jrde:base
MAINTAINER xiaokexiang <xxiaokexiang@gmail.com>
WORKDIR /opt

# kt-connect
COPY ktctl kubectl kt.sh /usr/local/bin/
RUN mkdir -p /root/.kube/ && chmod +x /usr/local/bin/kt.sh
COPY config.sample /root/.kube/

# 安装 jdk8
RUN wget https://repo.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.tar.gz -O /opt/zulu8.tar.gz  && \
    mkdir -p /opt/java && \
    tar -xzf /opt/zulu8.tar.gz -C /opt/java --strip-components=1 && \
    rm /opt/zulu8.tar.gz
ENV JAVA_HOME=/opt/java
ENV PATH=${PATH}:${JAVA_HOME}/bin

RUN wget https://download.jetbrains.com/idea/ideaIC-2022.3.tar.gz -O /opt/ideaIC-2022.3.tar.gz && \
    mkdir -p /opt/idea && \
    tar -xzf /opt/ideaIC-2022.3.tar.gz -C /opt/idea --strip-components=1 && \
    rm /opt/ideaIC-2022.3.tar.gz
ENV IDEA_HOME=/opt/idea
ENV PATH=${PATH}:${IDEA_HOME}/bin

# 安装 maven3
RUN wget https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz -O /opt/maven3.tar.gz && \
    mkdir -p /opt/maven3 && \
    tar -xzf /opt/maven3.tar.gz -C /opt/maven3 --strip-components=1 && \
    rm /opt/maven3.tar.gz
ENV MAVEN_HOME=/opt/maven3
ENV PATH=${PATH}:${MAVEN_HOME}/bin

# POSTMAN
RUN wget https://dl.pstmn.io/download/latest/linux_64 -O /opt/postman.tar.gz && \
    tar -zxvf postman.tar.gz -C /opt/postman --strip-components=1 && \
    ln -s /opt/postman/Postman /usr/local/bin/postman && \
    rm postman.tar.gz


COPY settings-20200707.xml settings-upms.xml /opt/maven3/conf
COPY ja-etfilter.jar /opt/idea
COPY idea.desktop /usr/share/applications/
COPY idea.desktop /root/桌面/idea.desktop
COPY postman.desktop /root/桌面/postman.desktop
RUN chmod +x /usr/share/applications/idea.desktop && chmod +x /root/桌面/idea.desktop && chmod +x /root/桌面/postman.desktop
