name: Build Docker image For jrde

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get label value from Dockerfile
        id: get_label
        run: |
          label=$(awk -F '=' '/^LABEL\s+VERSION=/ {print $2}' Dockerfile)
          echo "::set-output name=label::$label"

      - name: Build Docker image
        run: |
          docker build -t xiaokexiang/jrde:${{ steps.get_label.outputs.label }} .
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push the Docker image to DockerHub
        run: |
          docker push xiaokexiang/jrde:${{ steps.get_label.outputs.label }}
